### ISSUE TITLE
Void overflow doesn't seem to work with AE2

### ISSUE THREAD

**Issue by WhitePhant0m** [Natanaelel/BankStorage#20] opened 2024-04-05 11:20 UTC
**Mod version**
1.0.2

**Describe the bug**
Had an ME system insert items into a bank which was in a dock, didn't void overflow items(deepslate)

**To Reproduce**
fill a slot in a bank,
have it on void overflow,
have ae2 insert more items with ex. storage bus,
it now uses a new slot.

**Expected behavior**
Void overflow working with AE2

**Screenshots**
![image](https://github.com/Natanaelel/BankStorage/assets/33400200/80a1d1bd-df62-4fcb-a083-7ae4e5442926)
Reason for the amount of deepslate is another bug(dupe...).

Haven't tested via other item insertion methods than ae2, but think it will be the same?

**Comment by Natanaelel** [comment] 2024-04-05 11:32
This is intended behaviour. Items will only get voided it there isn't another free slot. Do you think this should be changed?
The dupe bug, is that related to this mod?

**Comment by WhitePhant0m** [comment] 2024-04-05 11:36
I feel like it should void regarless if free slots are available or not, since if the slot gets full, at least i feel like i have enough items in the bank.

about the dupe bug, it's related to the restock option of [ae2wtlib](https://github.com/Mari023/AE2WirelessTerminalLibrary)

**Comment by Natanaelel** [comment] 2024-04-05 11:42
I'm interested in the dupe. Can you explain it?

**Comment by WhitePhant0m** [comment] 2024-04-05 11:45
https://www.youtube.com/watch?v=u8bGZx-UHfs
Here's the link to it.

**Comment by WhitePhant0m** [comment] 2024-04-05 11:50
Also opened an issue on ae2wtlib's side https://github.com/Mari023/AE2WirelessTerminalLibrary/issues/258

**Comment by Natanaelel** [comment] 2024-04-05 11:58
Pretty sure I found the cause. Will test the fix in aof7.

**Comment by WhitePhant0m** [comment] 2024-04-05 12:22
It's a locked slot from inventory profiles next, though shouldn't matter, I just not made sure to toggle it off and it still dupes.

**Comment by Natanaelel** [comment] 2024-04-05 13:44
Fixed in next update.

**Comment by Natanaelel** [comment] 2024-04-21 13:25
Fixed in version 1.1.0
https://modrinth.com/mod/bank-storage/version/1.1.0

**Closed by Natanaelel** 2024-04-21 13:25 UTC
Labels: bug
